kind: destination
spec:
  name: mysql
  path: cloudquery/mysql
  registry: cloudquery
  version: "v2.8.2"
  spec:
    connection_string: "host=127.0.0.1;port=7777;user=root;password=cve;dbname=cvedatabase"
